authoraccount/urls.py
from django.urls import path
from . import views

app_name = "author"

urlpatterns = [
    path("statics/", views.statics_view, name="statics"),
    path("list/", views.list_view, name="list"),
    path("login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("activate/<slug>/", views.activate_account_code_view, name="activate"),
    path("logout/", views.logout_view, name="logout"),
    path("change-password/", views.password_change_view, name="change-password"),
    path("reset/", views.reset_password_view, name="reset"),
    path("reset-complete/<slug>/", views.reset_password_complete_view, name="reset-complete"),
    path("info/", views.info_view, name="info"),
    path("book-create/", views.book_create_view, name="book-create"),
    path("book-list/", views.book_list_view, name="book-list"),
    path("book-update/<int:id>/", views.book_update_view, name="book-update"),
    path("book-delete/<int:id>/", views.book_delete_view, name="book-delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("books.urls")),
    path("user/", include("useraccount.urls")),
    path("author/", include("authoraccount.urls")),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.contrib.auth import get_user_model
from ckeditor.fields import RichTextField
from services.generator import CodeGenerator
from services.slugify import slugify
from services.uploader import Uploader
from mptt.models import MPTTModel, TreeForeignKey
from authoraccount.models import Author
from useraccount.models import User
from django.db.models import Q
from services.mixin import DateMixin, SlugMixin
import json

Users = get_user_model()

warehouse = (
    ("Mövcuddur", "Mövcuddur"),
    ("Bitdi", "Bitdi"),
    ("Gözlənilir", "Gözlənilir")
)

status = (
    ("Aktiv", "Aktiv"),
    ("Deaktiv", "Deaktiv")
)

class Category(DateMixin, SlugMixin, MPTTModel):
    name = models.CharField(max_length=300, blank=True, null=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='children')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("-created_at",)
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def save(self, *args, **kwargs):
        self.code = CodeGenerator.create_activation_link_code(size=20, model_=Category)
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    @property
    def product_count(self):
        return Book.object.filter(
            Q(category_id=self.id) | Q(category__parent_id=self.id)
        ).count()


class Book(DateMixin, SlugMixin):
    userauthor = models.ForeignKey(Author, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=300, blank=True, null=True)
    summary = RichTextField(blank=True, null=True)
    author = models.CharField(max_length=300, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    release_date = models.PositiveIntegerField(blank=True, null=True)
    rent = models.FloatField(blank=True, null=True)
    r_month = models.CharField(max_length=2500, blank=True, null=True)
    quantity = models.PositiveIntegerField(blank=True, null=True)
    warehouse = models.CharField(max_length=200, choices=warehouse, blank=True, null=True)
    wishlist = models.ManyToManyField(User, blank=True, null=True)
    status = models.CharField(max_length=200, choices=status, blank=True, null=True)
    view_count = models.PositiveIntegerField(blank=True, null=True)
    wishlist_count = models.PositiveIntegerField(blank=True, null=True)

    def set_list_field(self, value):
        self.r_month = json.dumps(value)

    def get_list_field(self):
        return json.loads(self.r_month)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        ordering = ("-created_at",)
        verbose_name = "Book"
        verbose_name_plural = "Books"

    def save(self, *args, **kwargs):
        self.code = CodeGenerator.create_activation_link_code(size=20, model_=Book)
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class BookImage(DateMixin):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(upload_to=Uploader.upload_image_book, blank=True, null=True)

    def __str__(self):
        return self.book.name

    class Meta:
        ordering = ("-created_at", )
        verbose_name = "Book Image"
        verbose_name_plural = "Book Images"


class Comment(DateMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, blank=True, null=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} --- {self.book.name}'

    class Meta:
        ordering = ("-created_at", )
        verbose_name = "Comment"
        verbose_name_plural = "Comments"


class Contact(DateMixin):
    name = models.CharField(max_length=300, blank=True, null=True)
    email = models.CharField(max_length=320, blank=True, null=True)
    message = RichTextField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("-created_at", )
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"


class Queue(DateMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f'{self.user.name} --- {self.book.name}'

    class Meta:
        ordering = ("-created_at",)
        verbose_name = "Queue"
        verbose_name_plural = "Queues"


class RentBook(DateMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, blank=True, null=True)
    quantity_book = models.PositiveIntegerField(blank=True, null=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.book.name

    class Meta:
        ordering = ("-created_at", )
        verbose_name = "Rent Book"
        verbose_name_plural = "Rent Books"


class Cart(DateMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True, blank=True)
    month = models.PositiveIntegerField(null=True, blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} --- {self.book.name}"

class OrderItem(DateMixin):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.book.name

class Order(DateMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    items = models.ManyToManyField(OrderItem, blank=True, null=True)

    def __str__(self):
        return self.user.name


class OrderInfo(DateMixin):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, blank=True, null=True)
    quantity = models.PositiveIntegerField(blank=True, null=True)
    bookuserauthor = models.ForeignKey(Author, on_delete=models.CASCADE, blank=True, null=True)
    authorearning = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return f'{self.user} -- {self.user}'

    class Meta:
        ordering = ("-created_at",)
        verbose_name = "Order Info"
        verbose_name_plural = "Order Infos"

templates/author/activate.html
{% load static %}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Şifrəni Yenilə</title>
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/auth.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <div class="auth-content">
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <img class="brand" src="{% static 'assets/images/main-logo.png' %}" width="180" alt="bootstraper logo">
                    </div>
                    <h6 class="mb-4 text-muted">Şifrəni Yenilə</h6>
                    <p class="text-muted text-start">E-poçt adresinizə göndərilən şifrəni daxil edin</p>
                    <form method="post">
						{% csrf_token %}
                        <div class="mb-3 text-start">
                            {{code_active.activation_code.label}}
                            {{code_active.activation_code}}

                            {% if code_active.activation_code.errors %}
                                {% for error in code_active.activation_code.errors %}
                                    <li style="color: red"> {{ error|escape }} </li>
                                {% endfor %}
                            {% endif %}

                            {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                        <li style="color: red" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        <button type="submit" class="btn btn-primary shadow-2 mb-4">Göndər</button>
                    </form>
                    <p class="mb-0 text-muted">Hesabınız yoxdur? <a href="/author/register/">Qeydiyyatdan Keçin</a></p>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/author/book_create.html
{% extends 'author-base.html' %}
{% block body %}
{% load static %}

{{ block.super }}

			<div class="content">
                <div class="container">
                    <div class="page-title">
                        <h3>Yeni Kitab Paylaş</h3>
                    </div>
					<div class="col-lg-12">

                                    <form accept-charset="utf-8" method="post" enctype="multipart/form-data">
						                {% csrf_token %}
                                        <div class="row g-2">
                                            <div class="mb-3 col-md-6">
                                                {{ bookCreate.name.label }}
                                                {{ bookCreate.name }}

                                                {% if bookCreate.name.errors %}
                                                    {% for error in bookCreate.name.errors %}
                                                        <li style="color: red"> {{ error|escape }}</li>
                                                    {% endfor %}
                                                {% endif %}

                                                {% if messages %}
                                                    <ul class="messages">
                                                        {% for message in messages %}
                                                            <li style="color: red" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                                        {% endfor %}
                                                    </ul>
                                                {% endif %}
                                            </div>
                                            <div class="mb-3 col-md-6">
                                                {{ bookCreate.author.label }}
                                                {{ bookCreate.author }}

                                                {% if bookCreate.author.errors %}
                                                    {% for error in bookCreate.author.errors %}
                                                        <li style="color: red"> {{ error|escape }} </li>
                                                    {% endfor %}
                                                {% endif %}
                                            </div>
                                        </div>
                                        <div class="mb-3">
                                            {{ bookCreate.summary.label }} <br>
                                            {{ bookCreate.summary }} <br>

                                            {% if bookCreate.summary.errors %}
                                                {% for error in bookCreate.summary.errors %}
                                                    <li style="color: red"> {{ error|escape }} </li>
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                        <div class="row g-2">
                                            <div class="mb-3 col-md-6">
                                                {{ bookCreate.category.label }}
								                {{ bookCreate.category }}
                                            </div>
                                            <div class="mb-3 col-md-4">
                                                {{ bookCreate.release_date.label }}
                                                {{ bookCreate.release_date }}

                                                {% if bookCreate.release_date.errors %}
                                                    {% for error in bookCreate.release_date.errors %}
                                                        <li style="color: red"> {{ error|escape }} </li>
                                                    {% endfor %}
                                                {% endif %}
                                            </div>
                                            <div class="mb-3 col-md-2">
                                                {{ bookCreate.rent.label }}
                                                {{ bookCreate.rent }}

                                                {% if bookCreate.rent.errors %}
                                                    {% for error in bookCreate.rent.errors %}
                                                        <li style="color: red"> {{ error|escape }} </li>
                                                    {% endfor %}
                                                {% endif %}
								                <span class="mt-3" id="rent_calculate"></span> <br>
                                            </div>
                                        </div>
                                        Kiralama ayı <span class="text-muted"> - Ən çox 3 seçim edə bilərsiniz və bu seçimlər sonradan dəyişdirilə bilməz*</span>
                                        <div class="row">
                                            <div class="mb-3 col-md-2">
                                                <div class="form-check">
                                                  <input class="form-check-input" name="rent-month" type="checkbox" value="1" id="oneM">
                                                  <label class="form-check-label" for="oneM">
                                                    1 Ay
                                                  </label>
                                                </div>
                                                <div class="form-check">
                                                  <input class="form-check-input" name="rent-month" type="checkbox" value="3" id="threeM">
                                                  <label class="form-check-label" for="threeM">
                                                    3 Ay
                                                  </label>
                                                </div>
                                            </div>
                                            <div class="mb-3 col-md-2">
                                                <div class="form-check">
                                                  <input class="form-check-input" name="rent-month" type="checkbox" value="6" id="sixM">
                                                  <label class="form-check-label" for="sixM">
                                                    6 Ay
                                                  </label>
                                                </div>
                                                <div class="form-check">
                                                  <input class="form-check-input" name="rent-month" type="checkbox" value="9" id="nineM">
                                                  <label class="form-check-label" for="nineM">
                                                    9 Ay
                                                  </label>
                                                </div>
                                            </div>
                                            <div class="mb-3 col-md-2">
                                                <div class="form-check">
                                                  <input class="form-check-input" name="rent-month" type="checkbox" value="12" id="twelveM">
                                                  <label class="form-check-label" for="twelveM">
                                                    12 Ay
                                                  </label>
                                                </div>
                                            </div>
                                            <div class="mb-3 col-md-4 ms-auto">
                                                {{ bookImageCreateForm.image.label }} <br>
                                                {{ bookImageCreateForm.image }}

                                                {% if bookImageCreateForm.image.errors %}
                                                    {% for error in bookImageCreateForm.image.errors %}
                                                        <li style="color: red">{{ error|escape }} </li>
                                                    {% endfor %}
                                                {% endif %}
                                            </div>
                                        </div>
                                        <div class="row g-2">
                                            <div class="mb-3 col-md-4">
                                                {{ bookCreate.quantity.label }}
								                {{ bookCreate.quantity }}
                                            </div>
                                            <div class="mb-3 col-md-4">
                                                {{ bookCreate.warehouse.label }}
                                                {{ bookCreate.warehouse }}

                                                {% if bookCreate.warehouse.errors %}
                                                    {% for error in bookCreate.warehouse.errors %}
                                                        <li style="color: red">{{ error|escape }} </li>
                                                    {% endfor %}
                                                {% endif %}
                                            </div>
                                            <div class="mb-4 col-md-4">
                                                {{ bookCreate.status.label }}
                                                {{ bookCreate.status }}
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-primary"><i class="fas fa-external-link-alt"></i>&nbsp;&nbsp; Paylaş </button>
                                    </form>
                                </div>
                            </div>
                        </div>

<script src="{% static 'assets/js/jquery-1.11.0.min.js' %}"></script>
<script>

    $(document).ready(function() {

        $('#id_rent').attr('maxlength', '3');

  		$('#id_rent').keyup(function() {
    		var inputValue = $(this).val();
    		if (inputValue>500) {
    		    $('#rent_calculate').html("3 aylıq kira qiyməti 500 AZN-dən yuxarı olmamalıdır");
    		} else if (inputValue<3) {
				$('#rent_calculate').html("3 aylıq kira qiyməti 3 AZN-dən aşağı olmamalıdır");
			} else {
			    $('#rent_calculate').html("");
			}
  		});
	});


const checkboxes = document.querySelectorAll('input[type=checkbox][name=rent-month]');
let checkedCount = 0;

checkboxes.forEach((checkbox) => {
  checkbox.addEventListener('change', () => {
    if (checkbox.checked) {
      checkedCount++;
    } else {
      checkedCount--;
    }

    if (checkedCount === 3) {
      checkboxes.forEach((cb) => {
        if (!cb.checked) {
          cb.disabled = true;
        }
      });
    } else {
      checkboxes.forEach((cb) => {
        cb.disabled = false;
      });
    }
  });
});
</script>

{% endblock %}

templates/author/book_update.html
{% extends 'author-base.html' %}
{% block body %}
{% load static %}

{{ block.super }}

			<div class="content">
                <div class="container">
                    <div class="page-title">
                        <h3>Kitabı Yenilə</h3>
                    </div>
					<div class="col-lg-12">

                                    <form accept-charset="utf-8" method="post" enctype="multipart/form-data">
						                {% csrf_token %}
                                        <div class="row g-2">
                                            <div class="mb-3 col-md-6">
                                                {{ BookForm.name.label }}
												{{ BookForm.name }}

												{% if BookForm.name.errors %}
													{% for error in BookForm.name.errors %}
														<li style="color: red"> {{ error|escape }} </li>
													{% endfor %}
												{% endif %}

												{% if messages %}
                                                    <ul class="messages">
                                                        {% for message in messages %}
                                                            <li style="color: red" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                                        {% endfor %}
                                                    </ul>
                                                {% endif %}
                                            </div>
                                            <div class="mb-3 col-md-6">
                                                {{ BookForm.author.label }}
												{{ BookForm.author }}

												{% if BookForm.author.errors %}
													{% for error in BookForm.author.errors %}
														<li style="color: red"> {{ error|escape }} </li>
													{% endfor %}
												{% endif %}
                                            </div>
                                        </div>
                                        <div class="mb-3">
                                            {{ BookForm.summary.label }} <br>
											{{ BookForm.summary }} <br>

											{% if BookForm.summary.errors %}
												{% for error in BookForm.summary.errors %}
													<li style="color: red"> {{ error|escape }} </li>
												{% endfor %}
											{% endif %}
                                        </div>
                                        <div class="row g-2">
                                            <div class="mb-3 col-md-4">
                                                {{ BookForm.category.label }}
												{{ BookForm.category }}
                                            </div>
                                            <div class="mb-3 col-md-4">
                                                {{ BookForm.release_date.label }}
												{{ BookForm.release_date }}

												{% if BookForm.release_date.errors %}
													{% for error in BookForm.release_date.errors %}
														<li style="color: red"> {{ error|escape }} </li>
													{% endfor %}
												{% endif %}
                                            </div>
                                            <div class="mb-3 col-md-4">
                                                {{ BookForm.rent.label }}
												{{ BookForm.rent }}

												{% if BookForm.rent.errors %}
													{% for error in BookForm.rent.errors %}
														<li style="color: red"> {{ error|escape }} </li>
													{% endfor %}
												{% endif %}

												<span id="rent_calculate"></span> <br>
                                            </div>
                                        </div>
                                        <div class="row g-2">
                                            <div class="mb-3 col-md-4">
                                                {{ BookForm.quantity.label }}
												{{ BookForm.quantity }}
                                            </div>
                                            <div class="mb-3 col-md-4">
                                                {{ BookForm.warehouse.label }}
												{{ BookForm.warehouse }}

												{% if BookForm.warehouse.errors %}
													{% for error in BookForm.warehouse.errors %}
														<li style="color: red"> {{ error|escape }} </li>
													{% endfor %}
												{% endif %}
                                            </div>
											<div class="mb-3 col-md-4">
                                                {{ BookForm.status.label }}
												{{ BookForm.status }}
                                            </div>
											<div class="mb-3 col-md-4 mt-3">
                                                {{ BookImageForm.image.label }} <br>
												{{ BookImageForm.image }}

												{% if BookImageForm.image.errors %}
													{% for error in BookImageForm.image.errors %}
														<li style="color: red"> {{ error|escape }} </li>
													{% endfor %}
												{% endif %}
                                            </div>
											<div class="mb-3 col-md-6 my-auto mx-auto">
												<img src="{{BookPhoto.image.url}}" width="100" alt="">
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-primary mt-3 mb-4"><i class="fas fa-pencil-alt"></i>&nbsp;&nbsp; Kitabı Yenilə </button>
                                    </form>
                                </div>
                            </div>
                        </div>

<script src="{% static 'assets/js/jquery-1.11.0.min.js' %}"></script>
<script>

    $(document).ready(function() {

        $('#id_rent').attr('maxlength', '3');

  		$('#id_rent').keyup(function() {
    		var inputValue = $(this).val();
    		if (inputValue>500) {
    		    $('#rent_calculate').html("3 aylıq kira qiyməti 500 AZN-dən yuxarı olmamalıdır");
    		} else if (inputValue > 2){
    			$('#rent_calculate').html("6 aylıq kiralama qiyməti - <strong>" + inputValue*3 + "</strong> <br> 1 illik kiralama qiyməti - <strong>" + inputValue*5 + "</strong>");
			} else {
				$('#rent_calculate').html("3 aylıq kira qiyməti 3 AZN-dən aşağı olmamalıdır");
			}
  		});
	});
</script>

{% endblock %}

templates/author/login.html
{% load static %}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Kirayəçi Girişi</title>
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/auth.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/fontawesome/css/fontawesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/fontawesome/css/solid.min.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <div class="auth-content">
            <div class="card">
                <div class="mt-2 ms-2">
                    <a style="text-decoration: none;" href="/">
                        <i style="font-size: 23px; color: grey" class="fas fa-sign-out-alt fa-rotate-180"></i>
                        <span style="font-size: 15px;">Ana Səhifə</span>
                    </a>
                </div>
                <div class="card-body text-center">
                    <div class="mb-4">
                        <img class="brand" src="{% static 'assets/images/main-logo.png' %}" width="200">
                    </div>
                    <h6 class="mb-4 text-muted">Kirayəçi Girişi</h6>
                    <form method="post">
						{% csrf_token %}
                        <div class="mb-3 text-start">
                        	{{ loginForm.username.label }}
							{{ loginForm.username }}

							{% if loginForm.username.errors %}
								{% for error in loginForm.username.errors %}
									<li style="color: red">{{ error|escape }} </li>
								{% endfor %}
							{% endif %}
						</div>
                        <div class="mb-3 text-start">
                        	{{ loginForm.password.label }}
							{{ loginForm.password }}

							{% if loginForm.password.errors %}
								{% for error in loginForm.password.errors %}
									<li style="color: red"> {{ error|escape }} </li>
								{% endfor %}
							{% endif %}
						</div>
                        <button type="submit" class="btn btn-primary shadow-2 mb-4">Giriş</button>
                    </form>
					<p id="loginNotification" style="color: green;">{{ loginSuccess }}</p> <br>
                    <p class="mb-2 text-muted">Şifrənizi unutdunuz? <a href="/author/reset/">Yenilə</a></p>
                    <p class="mb-0 text-muted">Hesabınız yoxdur? <a href="/author/register/">Qeydiyyatdan keçin</a></p>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script>
		const loginNotification = $("#loginNotification").text();

		if (loginNotification === "Giriş uğurlu. Yönləndirilirsiniz.."){
			setTimeout(function() {
				window.location.href = "/author/statics/";
			}, 2000);
		}
	</script>
</body>

</html>