books/urls.py
from django.urls import path
from . import views

app_name = "books"
handler404 = 'books.views.handler404'

urlpatterns = [
    path("", views.index_view, name="index"),
    path("about/", views.about_view, name="about"),
    path("shop/", views.shop_view, name="shop"),
    path("cart/", views.cart_view, name="cart"),
    path("detail/<int:id>/", views.detail_view, name="detail"),
    path("delcomment/", views.delcomment_view, name="delcomment"),
    path("wish/", views.wish_view, name="wish"),
    path("queue/", views.queue_view, name="queue"),
    path("createcart/", views.book_cart_create_view, name="createcart"),
    path("contact/", views.contact_view, name="contact"),
    path("base/", views.base_view, name="base"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("books.urls")),
    path("user/", include("useraccount.urls")),
    path("author/", include("authoraccount.urls")),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

useraccount/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("activate/<slug>/", views.activate_account_code_view, name="activate"),
    path("logout/", views.logout_view, name="logout"),
    path("change-password/", views.password_change_view, name="change-password"),
    path("reset/", views.reset_password_view, name="reset"),
    path("reset-complete/<slug>/", views.reset_password_complete_view, name="reset-complete"),
    path("info/", views.info_view, name="info"),
    path("wishlist/", views.wishlist_view, name="wishlist"),
    path("delwish/", views.delwish_view, name="delwish"),
    path("queue/", views.queue_view, name="queue"),
    path("delqueue/", views.delqueue_view, name="delqueue"),
    path("cart/", views.cart_view, name="cart"),
    path("delcart/", views.delete_cart_view, name="delcart"),
    path("payment/<redirectlink>/", views.payment_view, name="payment"),
]

books/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    name = forms.CharField(min_length=2, max_length=300, label="Adınız")
    email = forms.EmailField(min_length=3, max_length=320, label="E-poçt adresiniz")
    message = forms.CharField(min_length=5, max_length=2000, label="Mesajınız", widget=forms.Textarea())
    class Meta:
        model = Contact
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                "class": "u-full-width"
            })

    def clean(self):
        name = self.cleaned_data.get('name')

        if name:
            if not name.replace(" ", "").replace(",", "").replace(".", "").isalpha():
                self.add_error("name", "Adınızı doğru daxil edin")

books/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import ContactForm
from django.db.models import Case, When, CharField, F, Q, Sum, Value
from django.db.models.functions import Coalesce, Cast
from django.core.paginator import Paginator
from django.http import JsonResponse
from authoraccount.models import Author
from useraccount.models import User
from django.db.models import Avg, Max
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required

def handler404(request, exception):
    return render(request, '404.html', status=404)


def index_view(request):
    homebook = None
    featuredBooks = None
    bestSellingBook = None

    if Book.objects.all():
        homebook = Book.objects.filter(~Q(warehouse="Bitdi")&~Q(status="Deaktiv")).annotate(
            author_none=Coalesce(F("author"), Value("Qeyd olunmayıb"))
        ).order_by('-view_count')[0]

        featuredBooks = Book.objects.filter(~Q(warehouse="Bitdi")&~Q(status="Deaktiv")).annotate(
            author_none=Coalesce(F("author"), Value("Qeyd olunmayıb"))
        ).order_by('-view_count')[:4]

        bestSellingBook = Book.objects.filter(~Q(warehouse="Bitdi")&~Q(status="Deaktiv")).annotate(
            author_none=Coalesce(F("author"), Value("Qeyd olunmayıb"))
        ).order_by('-view_count')[0]

    context = {
        "homebook": homebook,
        "featuredBooks": featuredBooks,
        "bestSellingBook": bestSellingBook
    }

    return render(request, "books/index.html", context)


def about_view(request):
    return render(request, "books/about.html", {})


def shop_view(request):
    books = Book.objects.filter(~Q(warehouse="Bitdi")&~Q(status="Deaktiv")).annotate(
        author_none=Coalesce(F("author"), Value("Qeyd olunmayıb"))
    )

    filter_, filter_dict = Q(), {}

    # ----------------

    years = Book.objects.filter((~Q(release_date=None)&~Q(warehouse="Bitdi")&~Q(status="Deaktiv"))).values_list('release_date', flat=True).distinct()

    # ----------------

    tenants = Author.objects.all()

    # ----------------

    category = request.GET.getlist("category", None)

    if category != "" and category:
        filter_dict["category"] = "".join(f'category={cat}&' for cat in category)
        filter_.add(Q(category__in=category), Q.AND)

    # ----------------

    tenant = request.GET.get("tenant", None)

    if tenant != "" and tenant:
        filter_dict["userauthor"] = tenant
        filter_.add(Q(userauthor=tenant), Q.AND)

   # ----------------

    year = request.GET.get("year", None)

    if year:
        filter_dict["release_date"] = year
        filter_.add(Q(release_date=year), Q.AND)

    # ----------------

    if request.method == "POST":
        search = request.POST.get("search")

        filter_.add(Q(name__icontains=search), Q.AND)


    books = books.filter(filter_)

    paginator = Paginator(books, 6)
    page = request.GET.get("page", 1)
    book_list = paginator.get_page(
        page)

    context = {
        "books": book_list,
        "categories": Category.objects.filter(parent__isnull=True),
        "years": set(years),
        "tenants": tenants,
        "pagiantor": paginator,
        "filter_dict": filter_dict.values()
    }

    return render(request, "books/shop.html", context)


def cart_view(request):
    context = {}
    return render(request, "books/cart.html", context)


def detail_view(request, id):
    books = get_object_or_404(Book.objects.filter(~Q(warehouse='Bitdi')&~Q(status='Deaktiv')).annotate(
        author_none=Coalesce(F("author"), Value("Qeyd olunmayıb"))
    ).annotate(
        release_date_none=Coalesce(F("release_date"), Value("Qeyd olunmayıb"), output_field=CharField())
    ).annotate(
        category_none=Coalesce(F("category"), Value("Qeyd olunmayıb"), output_field=CharField())
    ), id=id)

    books.view_count += 1
    books.save()


    # -------

    get_user = None

    if request.user.username:
        get_user = User.objects.get(username=request.user) if User.objects.filter(username=request.user).exists() else None

    if request.method == "POST" and "comment" in request.POST:
        comment = request.POST.get("comment")

        if not Comment.objects.filter(user=get_user).exists():
            Comment.objects.create(
                user=get_user,
                book=books,
                author=books.userauthor,
                comment=comment
            )

        return redirect(f"/detail/{books.id}")


    # -------

    month_prices = {}

    for month in books.get_list_field():
        month_prices[month] = int(month) * books.rent

    # -------

    user_qs = User.objects.filter(username=request.user).exists() if request.user.username else False

    check_user_cart = False
    check_user_queue = False

    if user_qs:
        get_user_c = User.objects.get(username=request.user)

        check_user_cart = get_user_c.cart_set.filter(Q(user=get_user_c)&Q(book=books)).exists()
        check_user_queue = get_user_c.queue_set.filter(Q(user=get_user_c)&Q(book=books)).exists()

    # ------

    comments = Comment.objects.filter(book=books.id) if Comment.objects.filter(book=books.id).exists() else None

    context = {
        "bookDetail": books,
        "get_user": get_user,
        "month_prices": month_prices,
        "check_user_cart": check_user_cart,
        "check_user_queue": check_user_queue,
        "comments": comments
    }

    return render(request, "books/detail.html", context)


@login_required(login_url="/user/login/")
def delcomment_view(request):
    data = {}
    get_object_or_404(User, username=request.user)

    comment = get_object_or_404(Comment, id=int(request.POST.get("id")))

    user_comment_vals = User.objects.get(username=request.user).comment_set.all()
    user_values = user_comment_vals.values_list("user", flat=True)
    # get user values from user's comment model

    get_user = User.objects.get(username=request.user)

    if all(user_id == get_user.id for user_id in user_values):
        # Checking that the person who deleted the comment is their own comment
        comment.delete()
        data["success"] = True
    else:
        data["permission"] = False

    return JsonResponse(data)


def wish_view(request):
    data = {}
    book = get_object_or_404(Book, id=int(request.POST.get("id")))

    user_qs = User.objects.filter(username=request.user).exists() if request.user.username else False

    if user_qs:
        get_user = User.objects.get(username=request.user)
        if get_user in book.wishlist.all():
            data["success"] = False
            book.wishlist.remove(get_user)
        else:
            book.wishlist_count += 1
            book.save()
            book.wishlist.add(get_user)
            data["success"] = True
    else:
        data["permission"] = False

    return JsonResponse(data)


def queue_view(request):
    data = {}
    book = get_object_or_404(Book, id=int(request.POST.get("id")))

    user_qs = User.objects.filter(username=request.user).exists() if request.user.username else False

    if user_qs:
        get_user = User.objects.get(username=request.user)
        if get_user.queue_set.filter(Q(user=get_user)&Q(book=book)):
            data["success"] = False
        else:
            Queue.objects.create(
                user=get_user,
                book=book
            )
            data["success"] = True
    else:
        data["permission"] = False

    return JsonResponse(data)


def book_cart_create_view(request):
    data = {}
    book = get_object_or_404(Book, id=int(request.POST.get("id")))

    user_qs = User.objects.filter(username=request.user).exists() if request.user.username else False

    check_user_cart = False

    if user_qs:
        get_user_c = User.objects.get(username=request.user)
        check_user_cart = get_user_c.cart_set.filter(Q(user=get_user_c) & Q(book=book)).exists()

        if request.method == "POST" and "month" in request.POST:
            user_qs_c = User.objects.filter(username=request.user).exists()

            if user_qs_c:
                get_user_c = User.objects.get(username=request.user)

                if not check_user_cart:
                    Cart.objects.get_or_create(
                        user=get_user_c,
                        book=book,
                        month=request.POST.get('month'),
                        author=book.userauthor
                    )

                    data["success"] = True

        data["check_user_cart"] = check_user_cart

    else:
        data["permission"] = False

    return JsonResponse(data)


def contact_view(request):
    contactForm = ContactForm()

    if request.method == "POST":
        contactForm = ContactForm(request.POST or None)

        if contactForm.is_valid():
            contactForm.save()

            # sending mail

            send_mail(
                'Booksaw Contact',  # subject
                contactForm.cleaned_data.get('message'),  # message
                'settings.EMAIL_HOST_USER',  # from mail
                ['youremail@gmail.com', ],  # to mail
                fail_silently=False,
            )

            return redirect("books:contact")


    context = {
        "contact": contactForm
    }

    return render(request, "books/contact.html", context)


def base_view(request):
    data = {}

    user_qs = Users.objects.filter(username=request.user).exists() if request.user.username else False

    if user_qs:
        get_user = Users.objects.get(username=request.user)
        if Author.objects.filter(username=Users.objects.get(username=get_user)).exists():
            data["account"] = "Author"
        elif User.objects.filter(username=Users.objects.get(username=get_user)).exists():
            data = {
                "account": "User",
                "cart_count": User.objects.get(username=request.user).cart_set.count()
            }

templates/books/detail.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/price-boxes.css' %}">

<style>
.wishlist-detail {
  font-size: 2.5rem;
  margin-bottom: 3.5rem;
  background-color: transparent !important;
  cursor: pointer;
  color: #878484;
}

.image-container {
  width: 80px;
  height: 80px;
  border-radius: 50%;
  overflow: hidden;
}


.image-container img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

</style>

	<header id="header">
		<div class="container">
			<div class="row">

				<div class="col-md-2">
					<div class="main-logo">
						<a href="/"><img src="{% static 'assets/images/main-logo.png' %}" alt="logo"></a>
					</div>

				</div>

				<div class="col-md-10">

					<nav id="navbar">
						<div class="main-menu stellarnav">
							<ul class="menu-list">
								<li class="menu-item"><a href="/" data-effect="Home">Ana Səhifə</a></li>
								<li class="menu-item active"><a href="/shop/" class="nav-link" data-effect="Shop">Kitablar</a></li>
								<li class="menu-item"><a href="/about/" class="nav-link" data-effect="About">Haqqımızda</a></li>
								<li class="menu-item"><a href="/contact/" class="nav-link" data-effect="Contact">Əlaqə</a></li>
							</ul>

							<div class="hamburger">
				                <span class="bar"></span>
				                <span class="bar"></span>
				                <span class="bar"></span>
				            </div>

						</div>
					</nav>

				</div>

			</div>
		</div>
	</header>

</div><!--header-wrap-->

<section class="bg-sand padding-large">
	<div class="container">
		<div class="row">

			<div class="col-md-6">
				<img src="{{ bookDetail.bookimage_set.first.image.url }}" width="400" class="product-image">
			</div>

			<div class="col-md-6 pl-5">

		<div class = "product-content">
          <h2 class = "product-title">{{ bookDetail.name }}</h2>
          <h4 class = "product-link">{{ bookDetail.author_none }}</h4>

          <div class = "product-detail">
            <ul>
              <li>Yazar: <span>{{ bookDetail.author_none }}</span></li>
              <li>Anbar: <span>{{ bookDetail.warehouse }}</span></li>
              <li>Miqdar: <span>{{ bookDetail.quantity }}</span></li>
				{% if bookDetail.category != None %}
              		<li>Kateqoriya: <span>{{ bookDetail.category }}</span></li>
				{% else %}
					<li>Kateqoriya: <span>Qeyd olunmmayıb</span></li>
				{% endif %}
              <li>Nəşr ili: <span>{{ bookDetail.release_date_none }}</span></li>
              <li>Paylaşan: <span>{{ bookDetail.userauthor.username.first_name }}</span></li>
              <li>Baxış sayı: <span>{{ bookDetail.view_count }}</span></li>
            </ul>
          </div>

	<form method="POST">
	{% csrf_token %}

		{% if bookDetail.warehouse != "Gözlənilir" and bookDetail.warehouse == "Mövcuddur" and check_user_cart == False %}

		<span> <strong>Kiralama müddətini seçin:</strong></span>

		<div class="price-select">

				{% for month, price in month_prices.items %}

				<div class="price_m">

					<input class="price_month" type="radio" id="price-option-{{month}}" name="month" value="{{month}}">
					<label for="price-option-{{month}}">
						<span class="selection-mark"></span>
						<span class="price-name"> {{month}} Aylıq</span>
						<span class="random-text"><span class="month_val" id="price-1">{{price|floatformat:2}}</span> AZN</span>
					</label>

				</div>

				{% endfor %}

		</div>

		{% endif %}

		<div class="purchase-info">

			{% if check_user_queue is True %}

			<button style="pointer-events: none; background-color: green"  class="btn">
				  Növbə Götürdünüz <i class="fas fa-shopping-cart"></i>
				</button>

			{% elif bookDetail.warehouse == "Gözlənilir" %}
				<button type="button" onclick="getQueue('{{bookDetail.id}}')" class="btn" title="Növbə götürdüyünüzdə, kitab anbarda mövcud olduqda sizə bildirim göndəriləcəkdir">
				  Növbə Götür <i class="fas fa-shopping-cart"></i>
				</button>

			{% endif %}

			{% if check_user_cart %}

            <button style="pointer-events: none; background-color: green" class="btn">
              Məhsulu Siyahınıza Əlavə Etdiniz
            </button>

			{% elif bookDetail.warehouse == "Mövcuddur" %}

			<button type="button" onclick="createCart('{{bookDetail.id}}')" class="btn">
              Məhsul Siyahısına Əlavə Et
            </button>

			{% endif %}

            <button type="button" title="İstək Siyahısına Əlavə Et" class="wishlist-detail" onclick="getWish('{{bookDetail.id}}')">
				<i style="{% if get_user in bookDetail.wishlist.all %} color: red; {% endif %}" id="wishlist" class="bi bi-heart-fill"></i>
			</button>
          </div>

			<h4 style="color: red; display: none;" id="permission-queue"></h4>
			<h4 style="color: red; display: none;" id="permission-wish"></h4>
			<h4 style="color: red; display: none;" id="permission-cart"></h4>

			<h2 style="margin-top: 4rem">Kitab məzmunu: </h2>

			<p>{{ bookDetail.summary|safe }}</p>

		</form>
		</div>

		</div>
			{% if get_user %}

			<form method="post">
			{% csrf_token %}
			<div style="margin-bottom: 60px" class="row">
				<div class="col-md-2 text-end">
					<div style="margin-left: 100px" class="image-container">
						{% if get_user.photo %}
							<img width="90" src="{{get_user.photo.url}}" alt="">
						{% endif %}
					</div>
				</div>
				<div class="col-md-1">
					<textarea class="u-full-width" name="comment" placeholder="Şərh əlavə edin" style="margin-bottom: 0px; width: 500px; height: 100px;"></textarea>
					<button style="margin-left: 390px; margin-top: 0px; height: 45px; font-size: 14px" type="submit">Əlavə Et</button>
				</div>

			</div>
			</form>

			{% endif %}

		</div>

		{% for comment in comments %}
		<hr>
		<div id="user_comment" style="margin-bottom: 50px" class="row">

			<div class="col-md-2 text-end">
				<div style="margin-left: 100px" class="image-container">
					{% if comment.user.photo %}
						<img id="ppCom" width="90" src="{{comment.user.photo.url}}" alt="">
					{% endif %}
				</div>
			</div>
			<div class="col-md-4 justify-context-start">
				<span style="margin-bottom: 20px">{{comment.user.username}}</span>
				<p><strong>{{comment.comment}}</strong></p>
			</div>
			{% if comment.user.username == request.user %}
			<div class="col-md-2 justify-context-start">
				<button onclick="delComment({{comment.id}})" style="border-radius: 10%; background-color: #c74e5c; height: 45px; font-size: 12px" type="button">Şərhinizi silin</button>
			</div>
			{% endif %}

		</div>
		{% endfor %}

	</div>
</section>

<script src="{% static 'assets/js/jquery-1.11.0.min.js' %}"></script>
<script>
	const search = $("#search-b");
   	search.hide();

	const wish_url = "{% url 'books:wish' %}"
	const permissionMsgWish = $("#permission-cart")

	function getWish(id){

		var myHeaders = new Headers()
           myHeaders.append('X-CSRFToken', document.querySelector('[name=csrfmiddlewaretoken]').value)

           var formData = new FormData()
           formData.append('id', id)

			var requestOptions = {
               method: 'POST',
                headers: myHeaders,
                body: formData,
                redirect: 'follow',
            };

            response = fetch(wish_url, requestOptions)
            	.then(function(response) {
                    if (response.ok) {
                        response.json().then((data) => {
                            if (data.permission == false){
                                permissionMsgWish.append("Əməliyyatı etmək üçün istifadəçi hesabına giriş etməlisiniz");
                            	permissionMsgWish.show();
								  setTimeout(function() {
									permissionMsgWish.hide();
								  }, 4000);
                            } else if (data.success) {
								$("#wishlist").css('color', 'red');
								location.reload()
                            } else{
                                $("#wishlist").css('color', 'white');
                                location.reload();
                            }

                        })

                    }
                })
		permissionMsgWish.html('')
		}


	const queue_url = "{% url 'books:queue' %}"
	const permissionMsgQueue = $("#permission-queue")

	function getQueue(id){

		var myHeaders = new Headers()
           myHeaders.append('X-CSRFToken', document.querySelector('[name=csrfmiddlewaretoken]').value)

           var formData = new FormData()
           formData.append('id', id)

			var requestOptions = {
               method: 'POST',
                headers: myHeaders,
                body: formData,
                redirect: 'follow',
            };

            response = fetch(queue_url, requestOptions)
            	.then(function(response) {
                    if (response.ok) {
                        response.json().then((data) => {
                            if (data.permission == false){
                                permissionMsgQueue.append("Əməliyyatı etmək üçün istifadəçi hesabına giriş etməlisiniz");
                            	permissionMsgQueue.show();
								  setTimeout(function() {
									permissionMsgQueue.hide();
								  }, 4000);
                            } else if (data.success) {
								location.reload()
                            }

                        })

                    }
                })
		permissionMsgQueue.html('')
		}


	$(document).ready(function() {
	  $('input[type="radio"]:first').prop('checked', true); // Automatically select the first entry when the page opens
	});

	const create_cart_url = "{% url 'books:createcart' %}"
	const permissionMsgCart = $("#permission-cart")

	function createCart(id){

		var myHeaders = new Headers()
           myHeaders.append('X-CSRFToken', document.querySelector('[name=csrfmiddlewaretoken]').value)

           var formData = new FormData()
           formData.append('id', id)
           formData.append('month', $('input[name=month]:checked').val())

			var requestOptions = {
               method: 'POST',
                headers: myHeaders,
                body: formData,
                redirect: 'follow',
            };

            response = fetch(create_cart_url, requestOptions)
            	.then(function(response) {
                    if (response.ok) {
                        response.json().then((data) => {
                            if (data.permission == false){
                                permissionMsgCart.append("Əməliyyatı etmək üçün istifadəçi hesabına giriş etməlisiniz");
                            	permissionMsgCart.show();
								  setTimeout(function() {
									permissionMsgCart.hide();
								  }, 4000);
                            } else if (data.success) {
                            	location.reload()
                            }

                        })

                    }
                })
		permissionMsgCart.html('')
		}


	const comment_url = "{% url 'books:delcomment' %}"

	function delComment(id){

		var myHeaders = new Headers()
           myHeaders.append('X-CSRFToken', document.querySelector('[name=csrfmiddlewaretoken]').value)

           var formData = new FormData()
           formData.append('id', id)

			var requestOptions = {
               method: 'POST',
                headers: myHeaders,
                body: formData,
                redirect: 'follow',
            };

            response = fetch(comment_url, requestOptions)
            	.then(function(response) {
                    if (response.ok) {
                        response.json().then((data) => {
                            if (data.success) {
								$("#user_comment").remove();
                            }
                            location.reload()
                        })

                    }
                })

		}

</script>

{% endblock %}

templates/books/shop.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

{{ block.super }}

	<header id="header">
		<div class="container">
			<div class="row">

				<div class="col-md-2">
					<div class="main-logo">
						<a href="/"><img src="{% static 'assets/images/main-logo.png' %}" alt="logo"></a>
					</div>

				</div>

				<div class="col-md-10">

					<nav id="navbar">
						<div class="main-menu stellarnav">
							<ul class="menu-list">
								<li class="menu-item"><a href="/" data-effect="Home">Ana Səhifə</a></li>
								<li class="menu-item active"><a href="/shop/" class="nav-link" data-effect="Shop">Kitablar</a></li>
								<li class="menu-item"><a href="/about/" class="nav-link" data-effect="About">Haqqımızda</a></li>
								<li class="menu-item"><a href="/contact/" class="nav-link" data-effect="Contact">Əlaqə</a></li>
							</ul>

							<div class="hamburger">
				                <span class="bar"></span>
				                <span class="bar"></span>
				                <span class="bar"></span>
				            </div>

						</div>
					</nav>

				</div>

			</div>
		</div>
	</header>

</div><!--header-wrap-->

<!--<div>-->
<!--	<div class="container">-->
<!--		<div class="row">-->
<!--			<div class="col-md-12">			-->
<!--				<div class="colored">-->
<!--					<h1 class="page-title">Shop</h1>-->
<!--					<div class="breadcum-items">-->
<!--						<span class="item"><a href="index.html">Home /</a></span>-->
<!--						<span class="item colored">Shop</span>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->
<!--</div>-->
<!--site-banner-->

<section class="padding-large">
	<div class="container">
		<div class="row">

			<div class="col-md-3">

				<form method="GET">
				
				<h3 class="filter-title">Kateqoriyalar</h3>
					<div class="filter-box">
						<div class="category-box">

							 {% for category in categories %}
								{% for categoryName in category.children.all %}
									<div class="line">
									  <input type="checkbox" class="my-checkbox-x2" name="category" id="category" value="{{ categoryName.id }}">
									  {{ categoryName.name }}
									</div>
								{% endfor %}
							{% endfor %}

						</div>
					</div>

				<h3 class="filter-title">Kirayəçi</h3>

					<div class="filter-box">
						<select name="tenant" id="tenant">
						  <option value="">Seçilməyib</option>
							{% for tenant in tenants %}
							  <option value="{{tenant.id}}">{{tenant.name}}</option>
							{% endfor %}
						</select>
					</div>

				<h3 class="filter-title">Nəşr İli</h3>

					<div class="filter-box">
						<select name="year" id="year">
						  <option value="">Seçilməyib</option>
							{% for year in years %}
							  <option value="{{year}}">{{year}}</option>
							{% endfor %}
						</select>
					</div>

					<input type="hidden" name="page" value="{{books.number}}"> <!-- for new filter on current page -->

					<button type="submit">Filtirlə</button>

				</form>

			</div>

			<div class="col-md-9">

			<div class="products-grid grid">

				{% for book in books %}

			  	<figure class="product-style">
					<a href="{% url 'books:detail' book.id %}">
						<img src="{{ book.bookimage_set.first.image.url }}" alt="Books" class="product-item">
					</a>
					<figcaption>
						<h3> {{ book.name }} </h3>
						<p style="font-size: 18px;">Yazar: {{book.author_none|truncatewords:5 }} <br>
						<span style="font-size: 16px">Paylaşan: {{book.userauthor.name|truncatewords:5 }} </span></p>
						<div class="item-price"> {{book.rent}} AZN </div>
					</figcaption>
				</figure>

				{% endfor %}

	    	</div>

			<center>

			{% if pagiantor.num_pages > 1 %}

				<div class="pagination_section">
					{% if books.has_previous %}
            			<a href="?page={{ books.previous_page_number }}&{% for val in filter_dict %}{{val}}{% endfor %}"><< </a>
					{% endif %}

						{% for i in books.paginator.page_range %}
							<a href="?page={{i}}&{% for val in filter_dict %}{{val}}{% endfor %}" {% if books.number == i %} class="active" {% endif %}>{{i}}</a>
						{% endfor %}

					{% if books.has_next %}
            			<a href="?page={{ books.next_page_number }}&{% for val in filter_dict %}{{val}}{% endfor %}"> >></a>
					{% endif %}
        		</div>

			{% endif %}

			</center>

		</div>
	</div>


	</div>
</section>

<script src="{% static 'assets/js/jquery-1.11.0.min.js' %}"></script>
<script>
	const search = $("#search-b");
   	search.show();
</script>

{% endblock %}