books/urls.py
from django.urls import path
from . import views

app_name = "books"
handler404 = 'books.views.handler404'

urlpatterns = [
    path("", views.index_view, name="index"),
    path("about/", views.about_view, name="about"),
    path("shop/", views.shop_view, name="shop"),
    path("cart/", views.cart_view, name="cart"),
    path("detail/<int:id>/", views.detail_view, name="detail"),
    path("delcomment/", views.delcomment_view, name="delcomment"),
    path("wish/", views.wish_view, name="wish"),
    path("queue/", views.queue_view, name="queue"),
    path("createcart/", views.book_cart_create_view, name="createcart"),
    path("contact/", views.contact_view, name="contact"),
    path("base/", views.base_view, name="base"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("books.urls")),
    path("user/", include("useraccount.urls")),
    path("author/", include("authoraccount.urls")),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/author-base.html
{% load static %}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Kirayəçi Hesabı</title>
    <link href="{% static 'assets/vendor/fontawesome/css/fontawesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/fontawesome/css/solid.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/fontawesome/css/brands.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/master.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/flagiconcss/css/flag-icon.min.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <!-- sidebar navigation component -->
        <nav id="sidebar" class="">
            <div class="sidebar-header">
                <a href="/"><img src="{% static 'assets/images/main-logo.png' %}" width="100" alt="bootraper logo" class="app-logo"></a>
            </div>
            <ul class="list-unstyled components text-secondary">
                <li>
                    <a href="/author/statics/"><i class="fas fa-home"></i>İstatistika</a>
                </li>
                <li>
                    <a href="/author/info/"><i class="fas fa-file-alt"></i>Bilgilər</a>
                </li>
                <li>
                    <a href="/author/book-list/"><i class="fas fa-solid fa-book"></i>Kitablar</a>
                </li>
            </ul>
        </nav>
        <div id="body" class="active">
            <!-- navbar navigation component -->
            <nav class="navbar navbar-expand-lg navbar-white bg-white">
                <button type="button" id="sidebarCollapse" class="btn btn-light">
                    <i class="fas fa-bars"></i><span></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ms-auto">
                        <li class="nav-item dropdown">
                            <div class="nav-dropdown">
                                <a href="#" id="nav1" class="nav-item nav-link dropdown-toggle text-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fas fa-link"></i> <span>Qısa Linklər</span> <i style="font-size: .8em;" class="fas fa-caret-down"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-end nav-link-menu" aria-labelledby="nav1">
                                    <ul class="nav-list">
                                        <li><a href="/" class="dropdown-item"><i class="fas fa-home"></i> Ana Səhifə </a></li>
                                        <div class="dropdown-divider"></div>
                                        <li><a href="/shop/" class="dropdown-item"><i class="fas fa-book"></i> Kitablar Səhifəsi </a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <div class="nav-dropdown">
                                <a href="#" id="nav2" class="nav-item nav-link dropdown-toggle text-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fas fa-user"></i> <span id="account">{{request.user}}</span> <i style="font-size: .8em;" class="fas fa-caret-down"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-end nav-link-menu">
                                    <ul class="nav-list">
                                        <li><a id="logout" href="/author/logout/" class="dropdown-item"><i class="fas fa-sign-out-alt"></i> Çıxış Et </a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>

            {% block body %}
            {% endblock %}

        </div>
    </div>
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/script.js' %}"></script>
</body>

</html>

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
	<head>
		<title>Kitabxana</title>
		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <meta name="format-detection" content="telephone=no">
	    <meta name="apple-mobile-web-app-capable" content="yes">
	    <meta name="author" content="">
	    <meta name="keywords" content="">
	    <meta name="description" content="">

	    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/normalize.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'assets/icomoon/icomoon.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/vendor.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

		<!-- script
		================================================== -->
		<script src="{% static 'assets/js/modernizr.js' %}"></script>

	</head>

<body>

<div id="header-wrap">

	<div class="top-content">
		<div class="container">
			<div class="row">
				<div class="col-md-2">
					<div class="social-links">
						<h4 class="top"><a href="/">BOOKSAW</a></h4>
					</div><!--social-links-->
				</div>

				{% csrf_token %}

				<div class="col-md-10">
					<div class="right-element">
						<a href="/user/login/" id="user-account" class="user-account for-buy"><i class="bi bi-person"></i><span> İstifadəçi Hesabına Giriş </span></a>
						<a href="/author/login/" id="author-account" class="user-account for-buy"><i class="bi bi-person-check"></i><span> Kirayəçi Hesabına Giriş</span></a>

						<a href="/user/wishlist/" id="wishlist" class="wishlist for-buy"><i class="bi bi-heart"></i><span> İstək Siyahısı</span></a>
						<a href="/user/cart/" id="cart" class="cart for-buy"><i class="bi bi-bag"></i><span> Məhsul Siyahısı:(<span id="cart_n"></span>)</span></a>

						<div id="search-b" class="action-menu">

							<div class="search-bar">
								<a href="#" class="search-button search-toggle" data-selector="#header-wrap">
									<i class="icon icon-search"></i>
								</a>
								<form role="search" method="post" class="search-box">
									{% csrf_token %}
									<input class="search-field text search-input" minlength="3" name="search" placeholder="Kitab axtar" type="search">
								</form>
							</div>
						</div>

					</div><!--top-right-->
				</div>

			</div>
		</div>
	</div><!--top-content-->


    {% block body %}
    {% endblock %}



<footer id="footer">
	<div class="container">
		<div class="row">

			<div class="col-md-5">

				<div class="footer-item">
					<div class="company-brand">
						<img src="{% static 'assets/images/main-logo.png' %}" alt="logo" class="footer-logo">
						<p>BookSaw, kitabsevərlərin, tədqiqatçıların və tələbələrin kitab təminatında yeni dövrə başlamaq üçün müəyyən müddət ərzində yalnız rəqəmsal kitab almalarına və kirayə vermələrinə fürsət verən Rəqəmsal Nəşriyyat e-ticarət Platformasıdır.</p>
					</div>
				</div>

			</div>

			<div class="col-md-2">

				<div class="footer-menu">
					<h5>Haqqımızda</h5>
					<ul class="menu-list">
						<li class="menu-item">
							<a href="/shop/">Kitablar</a>
						</li>
						<li class="menu-item">
							<a href="/about/">Haqqımızda</a>
						</li>
						<li class="menu-item">
							<a href="/contact/">Əlaqə</a>
						</li>
					</ul>
				</div>

			</div>

			<div class="col-md-2">

				<div class="footer-menu">
					<h5>Hesab</h5>
					<ul class="menu-list">
						<li class="menu-item">
							<a href="/user/login/">İstifadəçi Girişi</a>
						</li>
						<li class="menu-item">
							<a href="/author/login/">Kirayəçi Girişi</a>
						</li>
					</ul>
				</div>

			</div>

			<div class="col-md-3">

				<div class="footer-menu">
					<h5>Dəstək</h5>
					<ul class="menu-list">
						<li class="menu-item">
							<a href="/contact/">Əlaqə Yarat</a>
						</li>
						<li class="menu-item">
							<a href="#">Gizlilik Siyasəti</a>
						</li>
						<li class="menu-item">
							<a href="#">İstifadəçi Şərtləri</a>
						</li>
					</ul>
				</div>

			</div>

		</div>
		<!-- / row -->

	</div>
</footer>

<div id="footer-bottom">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<div class="copyright">
					<div class="row">

						<div class="col-md-6">
							<p>© 2023 Bütün hüquqlar qorunur</p>
						</div>

						<div class="col-md-6">
							<div class="social-links align-right">
								<ul>
									<li>
										<a href="#"><i class="icon icon-facebook"></i></a>
									</li>
									<li>
										<a href="#"><i class="icon icon-twitter"></i></a>
									</li>
									<li>
										<a href="#"><i class="icon icon-youtube-play"></i></a>
									</li>
									<li>
										<a href="#"><i class="icon icon-behance-square"></i></a>
									</li>
								</ul>
							</div>
						</div>

					</div>
				</div><!--grid-->

			</div><!--footer-bottom-content-->
		</div>
	</div>
</div>
</div>
<script src="{% static 'assets/js/jquery-1.11.0.min.js' %}"></script>
<script src="{% static 'assets/js/plugins.js' %}"></script>
<script src="{% static 'assets/js/script-booksaw.js' %}"></script>
<script>


   		const base_url = "{% url 'books:base' %}"
   		const account = "{{ request.user }}"

		   var myHeader = new Headers()
           myHeader.append('X-CSRFToken', document.querySelector('[name=csrfmiddlewaretoken]').value)

           var formDatas = new FormData()
           formDatas.append('account', account)

			var requestsOptions = {
               method: 'POST',
                headers: myHeader,
                body: formDatas,
                redirect: 'follow',
            };

            response = fetch(base_url, requestsOptions)
            	.then(function(response) {
                    if (response.ok) {
                        response.json().then((data) => {
                            if (data.account == "User"){
                                $("#user-account").attr("href", "/user/info/");
                                $("#user-account span").text("User Hesabınız: {{request.user}}");
                                const cart_n = $("#cart_n")
   								cart_n.html(data.cart_count)
                            } else if (data.account == "Author") {
                            	$("#author-account").attr("href", "/author/info/");
                            	$("#author-account span").text("Kirayəçi Hesabınız: {{request.user}}");
                            }

                        })

                    }
                })


	</script>

</body>
</html>

templates/user-base.html
{% load static %}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>İstifadəçi Hesabı</title>
    <link href="{% static 'assets/vendor/fontawesome/css/fontawesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/fontawesome/css/solid.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/fontawesome/css/brands.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/master.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/flagiconcss/css/flag-icon.min.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <!-- sidebar navigation component -->
        <nav id="sidebar" class="">
            <div class="sidebar-header">
                <a href="/"><img src="{% static 'assets/images/main-logo.png' %}" width="100" alt="bootraper logo" class="app-logo"></a>
            </div>
            <ul class="list-unstyled components text-secondary">
                <li>
                    <a href="/user/info/"><i class="fas fa-file-alt"></i>Bilgilər</a>
                </li>
                <li>
                    <a href="/user/wishlist/"><i class="fas fa-heart"></i>İstək Siyahısı</a>
                </li>
                <li>
                    <a href="/user/cart/"><i class="fas fa-shopping-cart"></i>Məhsul Siyahısı</a>
                </li>
                <li>
                    <a href="/user/queue/"><i class="fas fa-clock"></i>Götürülən Növbələr</a>
                </li>
            </ul>
        </nav>
        <div id="body" class="active">
            <!-- navbar navigation component -->
            <nav class="navbar navbar-expand-lg navbar-white bg-white">
                <button type="button" id="sidebarCollapse" class="btn btn-light">
                    <i class="fas fa-bars"></i><span></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ms-auto">
                        <li class="nav-item dropdown">
                            <div class="nav-dropdown">
                                <a href="#" id="nav1" class="nav-item nav-link dropdown-toggle text-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fas fa-link"></i> <span>Qısa Linklər</span> <i style="font-size: .8em;" class="fas fa-caret-down"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-end nav-link-menu" aria-labelledby="nav1">
                                    <ul class="nav-list">
                                        <li><a href="/" class="dropdown-item"><i class="fas fa-home"></i> Ana Səhifə </a></li>
                                        <div class="dropdown-divider"></div>
                                        <li><a href="/shop/" class="dropdown-item"><i class="fas fa-book"></i> Kitablar Səhifəsi </a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <div class="nav-dropdown">
                                <a href="#" id="nav2" class="nav-item nav-link dropdown-toggle text-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fas fa-user"></i> <span id="account">{{request.user}}</span> <i style="font-size: .8em;" class="fas fa-caret-down"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-end nav-link-menu">
                                    <ul class="nav-list">
                                        <li><a id="logout" href="/user/logout/" class="dropdown-item"><i class="fas fa-sign-out-alt"></i> Çıxış Et </a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>

            {% block body %}
            {% endblock %}

        </div>
    </div>
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/script.js' %}"></script>
</body>

</html>