core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("books.urls")),
    path("user/", include("useraccount.urls")),
    path("author/", include("authoraccount.urls")),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

useraccount/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("register/", views.register_view, name="register"),
    path("activate/<slug>/", views.activate_account_code_view, name="activate"),
    path("logout/", views.logout_view, name="logout"),
    path("change-password/", views.password_change_view, name="change-password"),
    path("reset/", views.reset_password_view, name="reset"),
    path("reset-complete/<slug>/", views.reset_password_complete_view, name="reset-complete"),
    path("info/", views.info_view, name="info"),
    path("wishlist/", views.wishlist_view, name="wishlist"),
    path("delwish/", views.delwish_view, name="delwish"),
    path("queue/", views.queue_view, name="queue"),
    path("delqueue/", views.delqueue_view, name="delqueue"),
    path("cart/", views.cart_view, name="cart"),
    path("delcart/", views.delete_cart_view, name="delcart"),
    path("payment/<redirectlink>/", views.payment_view, name="payment"),
]

templates/user/activate.html
{% load static %}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Şifrəni Yenilə</title>
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/auth.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <div class="auth-content">
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <img class="brand" src="{% static 'assets/images/main-logo.png' %}" width="180" alt="bootstraper logo">
                    </div>
                    <h6 class="mb-4 text-muted">Şifrəni Yenilə</h6>
                    <p class="text-muted text-start">E-poçt adresinizə göndərilən şifrəni daxil edin</p>
                    <form method="post">
						{% csrf_token %}
                        <div class="mb-3 text-start">
                            {{code_active.activation_code.label}}
                            {{code_active.activation_code}}

                            {% if code_active.activation_code.errors %}
                                {% for error in code_active.activation_code.errors %}
                                    <li style="color: red"> {{ error|escape }} </li>
                                {% endfor %}
                            {% endif %}

                            {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                        <li style="color: red" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}

                        </div>
                        <button type="submit" class="btn btn-primary shadow-2 mb-4">Göndər</button>
                    </form>
                    <p class="mb-0 text-muted">Hesabınız yoxdur? <a href="/user/register/">Qeydiyyatdan Keçin</a></p>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/user/cart.html
{% extends 'user-base.html' %}
{% block body %}
{% load static %}

{{ block.super }}

            <div class="content">
                <div class="container-fluid">
                    <div class="page-title">
                        <h3>Məhsul Siyahısı</h3>
                    </div>

                    <form method="POST"> <!--  action="{% url 'user:payment' user.slug %}" -->
                    {% csrf_token %}

                    <div class="row w-100">
                        <div class="col-lg-12 col-md-12 col-12">
                            <p style="font-size: 1.1rem" class="mb-5 text-start">
                               Siyahınızda <i class="text-info font-weight-bold"><strong>{{ carts|length }}</strong></i> kitab var </p>
                            <table id="shoppingCart" class="table table-condensed table-responsive">

                                <thead>
                                    <tr>
                                        <th style="width:45%">Kitab adı</th>
                                        <th style="width:10%">Mövcud Kitab Sayı</th>
                                        <th style="width:20%">Kirayə Qiyməti</th>
                                        <th style="width:13%">Miqdar</th>
                                        <th style="width:12%">Siyahıdan Sil</th>
                                    </tr>
                                </thead>
                                <tbody>

                                {% for cart, price in carts.items %}

                                    <tr>
                                        <td data-th="Product">
                                            <div class="row">
                                                <div class="col-md-2 text-left">
                                                    <img src="{{cart.book.bookimage_set.first.image.url}}" width="120" class="img-fluid d-none d-md-block rounded mb-2 shadow ">
                                                </div>
                                                <div class="col-md-9 text-left mt-sm-2">
                                                    <h5>{{cart.book.name}}</h5>
                                                    <p class="font-weight-light">{{cart.author_none}}</p>
                                                </div>
                                            </div>
                                        </td>
                                        <td data-th="Count">{{cart.book.quantity}}</td>
                                        <td data-th="Price">{{cart.month}} Aylıq - <span class="{{price|floatformat:2}}" id="r_price">{{price|floatformat:2}}</span>  AZN</td>
                                        <td data-th="Quantity">
                                            <input type="number" id="quantity-{{cart.id}}" name="quantity-{{cart.id}}" onkeydown="return false" class="form-control form-control-lg text-center" value="1" min="1" max="{{cart.book.quantity}}">
                                        </td>
                                        <td class="actions" data-th="">
                                            <div class="text-right">
                                                <button type="button" title="Məhsulu məhsul siyahınızdan silin" onclick="deleteCart('{{cart.id}}');" class="btn btn-white border-secondary bg-white btn-md mb-2">
                                                    <i style="color: red" class="fas fa-trash"></i>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>

                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>

                {% if carts.items|length != 0 %}

                    <div class="row mt-4 justify-content-end">
                        <div class="col-2">
                            <h5>Toplam qiymət:</h5>
                            <h4> <span> <input type="text"
                                               style="border: none; background-color: transparent; font-family: inherit; font-size: inherit; font-weight: inherit; color: inherit; cursor: not-allowed;"
                                               id="subtotal" name="subtotal" value="{{cart_total_price|floatformat:2}}"
                                               readonly> AZN </span></h4>

                        </div>
                        <div class="col-2 mt-4">
                           <button style="font-size: 1.2rem" type="submit" class="btn btn-primary mb-4 btn-lg pl-5 pr-5">Ödənişə Keç</button>
                        </div>
                    </div>

                {% else %}
                    <h5 class="text-danger text-center mt-3">Siyahınızda kitab yoxdur</h5>
                {% endif %}

                     </form>

                </div>
            </div>

<script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
<script>

    function calculateSubtotal(){
        let total = 0;

        $('tr td span').each(function() {
          total += parseFloat($(this).text().replace(',', '.'));
        });

        $('#subtotal').val(total.toFixed(2).replace('.', ','));
    }

    $("input[type='number']").on("change", function() {
        const getClass = $(this);
            const quantity = getClass.val();
            const spanValue = getClass.closest('tr').find('td span');
            const price = parseFloat(spanValue.attr('class').replace(",", "."));
            const totalPrice = quantity * price;
            spanValue.text(totalPrice.toFixed(2).replace(".", ","));

            calculateSubtotal()
      });


    const del_cart = "{% url 'user:delcart' %}"

	function deleteCart(id){

		var myHeaders = new Headers()
           myHeaders.append('X-CSRFToken', document.querySelector('[name=csrfmiddlewaretoken]').value)

           var formData = new FormData()
           formData.append('id', id)

			var requestOptions = {
               method: 'POST',
                headers: myHeaders,
                body: formData,
                redirect: 'follow',
            };

            response = fetch(del_cart, requestOptions)
            	.then(function(response) {
                    if (response.ok) {
                        response.json().then((data) => {
                        if (data.success) {
								location.reload()
                            }
                        })

                    }
                })

		}

</script>

{% endblock %}

templates/user/change_password.html
{% load static %}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Şifrəni Dəyiş</title>
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/auth.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/fontawesome/css/fontawesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/fontawesome/css/solid.min.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <div class="auth-content">
            <div class="card">
                <div class="mt-2 ms-2">
                    <a style="text-decoration: none;" href="/user/info/">
                        <i style="font-size: 23px; color: grey" class="fas fa-sign-out-alt fa-rotate-180"></i>
                        <span style="font-size: 15px;">Geri</span>
                    </a>
                </div>
                <div class="card-body text-center">
                    <div class="mb-4">
                        <img class="brand" src="{% static 'assets/images/main-logo.png' %}" width="180" alt="bootstraper logo">
                    </div>
                    <h6 class="mb-4 text-muted">Şifrə Dəyişmə</h6>
                    <form method="post">
						{% csrf_token %}
                        <div class="mb-3 text-start">
								{{ changePassForm.old_password.label }}
								{{ changePassForm.old_password }} <br>

								{% if changePassForm.old_password.errors %}
									{% for error in changePassForm.old_password.errors %}
										<li style="color: red"> {{ error|escape }} </li>
									{% endfor %}
								{% endif %}
                        </div>
						<div class="mb-3 text-start">
                            	{{ changePassForm.new_password1.label }}
								{{ changePassForm.new_password1 }} <br>

								{% if changePassForm.new_password1.errors %}
									{% for error in changePassForm.new_password1.errors %}
										<li style="color: red"> {{ error|escape }} </li>
									{% endfor %}
								{% endif %}
                        </div>
						<div class="mb-3 text-start">
								{{ changePassForm.new_password2.label }}
								{{ changePassForm.new_password2 }}

								{% if changePassForm.new_password2.errors %}
									{% for error in changePassForm.new_password2.errors %}
										<li style="color: red"> {{ error|escape }} </li>
									{% endfor %}
								{% endif %}
                        </div>
                        <button class="btn btn-primary shadow-2 mb-4">Şifrəni Dəyiş</button>
                    </form>
					<p class="mb-0 text-muted">Köhnə şifrənizi unutdunuz? <a href="/user/reset/">Şifrəni yeniləyin</a></p>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/user/info.html
{% extends 'user-base.html' %}
{% block body %}
{% load static %}

{{ block.super }}

<style>
.image-container {
  width: 120px;
  height: 120px;
  border-radius: 50%;
  overflow: hidden;
}


.image-container img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
</style>

            <div class="content">
                <div class="container">
                    <div class="page-title">
                        <h3>Bilgiləri Yenilə</h3>
                    </div>
                    <div class="row gx-5">
                        <div class="col-lg-8">
                            <form accept-charset="utf-8" method="post" action="" enctype="multipart/form-data">
						        {% csrf_token %}
                                <div class="mb-3">
                                    {{ updateUserForm.first_name.label }}
                                    {{ updateUserForm.first_name }}
                                </div>
                                <div class="mb-3">
                                    {{ updateUserForm.last_name.label }}
                                    {{ updateUserForm.last_name }}
                                </div>
                                <div class="mb-3">
                                    {{ updateUserForm.email.label }}
                                    {{ updateUserForm.email }}

                                    {% if updateUserForm.email.errors %}
                                        {% for error in updateUserForm.username.errors %}
                                            <li style="color: red"> {{ error|escape }}</li>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="mb-3">
                                    {{ updateRegForm.age.label }}
                                    {{ updateRegForm.age }}

                                    {% if updateRegForm.age.errors %}
                                        {% for error in updateRegForm.age.errors %}
                                            <li style="color: red"> {{ error|escape }}</li>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="mb-3">
                                    {{ updateRegForm.bio.label }} <br>
                                    {{ updateRegForm.bio }} <br>
                                </div>
                                <div class="mb-3">
                                    {% if photo_url == "" %}
									    <h4>Profil şəkili yoxdur</h4>
								    {% else %}
									Profil şəkili <br>

                                    <div class="image-container">
                                        <img class="mt-1" style="border-radius: 50%;" width="150" height="150" src="{{ photo_url }}">
                                    </div>
								    {% endif %}
                                </div>

                                <div class="mb-4">
								    {{ updateRegForm.photo }}

								    {% if updateRegForm.photo.errors %}
									    {% for error in updateRegForm.photo.errors %}
										    <li style="color: red"> {{ error|escape }}</li>
                                        {% endfor %}
								    {% endif %}
                                </div>
                                <div><p style="color: red;"> {{ warning }} </p></div>
                                <div class="row">
                                    <div class="col-4 mb-3">
                                        <input type="submit" value="Məlumatları Yenilə" class="btn btn-success">
                                    </div>
                                    <div class="col-2 mb-3">
                                       <a href="/user/change-password/"> <input type="button" value="Şifrəni Dəyiş" class="btn btn-outline-primary"> </a>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="col-lg-4">
                            <img style="margin-top: 50px" src="{% static 'assets/images/undraw_sign_up_n6im.svg' %}" width="300" alt="banner" class="banner-image">
                        </div>
                    </div>
                </div>
            </div>

{% endblock %}

templates/user/login.html
{% load static %}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>İstifadəçi Girişi</title>
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/auth.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/fontawesome/css/fontawesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/fontawesome/css/solid.min.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <div class="auth-content">
            <div class="card">
                <div class="mt-2 ms-2">
                    <a style="text-decoration: none;" href="/">
                        <i style="font-size: 23px; color: grey" class="fas fa-sign-out-alt fa-rotate-180"></i>
                        <span style="font-size: 15px;">Ana Səhifə</span>
                    </a>
                </div>
                <div class="card-body text-center">
                    <div class="mb-4">
                        <img class="brand" src="{% static 'assets/images/main-logo.png' %}" width="200">
                    </div>
                    <h6 class="mb-4 text-muted">İstifadəçi Girişi</h6>
                    <form method="post">
						{% csrf_token %}
                        <div class="mb-3 text-start">
                        	{{ loginForm.username.label }}
							{{ loginForm.username }}

							{% if loginForm.username.errors %}
								{% for error in loginForm.username.errors %}
									<li style="color: red">{{ error|escape }} </li>
								{% endfor %}
							{% endif %}
						</div>
                        <div class="mb-3 text-start">
                        	{{ loginForm.password.label }}
							{{ loginForm.password }}

							{% if loginForm.password.errors %}
								{% for error in loginForm.password.errors %}
									<li style="color: red"> {{ error|escape }} </li>
								{% endfor %}
							{% endif %}
						</div>
                        <button type="submit" class="btn btn-primary shadow-2 mb-4">Giriş</button>
                    </form>
					<p id="loginNotification" style="color: green;">{{ loginSuccess }}</p> <br>
                    <p class="mb-2 text-muted">Şifrənizi unutdunuz? <a href="/user/reset/">Yenilə</a></p>
                    <p class="mb-0 text-muted">Hesabınız yoxdur? <a href="/user/register/">Qeydiyyatdan keçin</a></p>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script>
		const loginNotification = $("#loginNotification").text();

		if (loginNotification === "Giriş uğurlu. Yönləndirilirsiniz.."){
			setTimeout(function() {
				window.location.href = "/shop/";
			}, 2000);
		}
	</script>
</body>

</html>

templates/user/queues.html
{% extends 'user-base.html' %}
{% block body %}
{% load static %}

{{ block.super }}

            <div class="content">
                <div class="container-fluid">
                    <div class="page-title">
                        <h3>Götürülən Növbələr</h3>
                    </div>

                    {% csrf_token %}

					 <div class="col-md-12 col-lg-12">
                            <div class="card">
                                <div class="card-header">Növbə götürdüyünüz kitablar</div>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Adı</th>
                                                    <th>Anbar</th>
                                                    <th>Növbə götürdüyünüz tarix</th>
                                                    <th>Növbəni ləğv et</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            {% for queue in queues %}
                                                <tr>
                                                    <td>{{queue.book.name}}</td>
                                                    <td>{{queue.book.warehouse}}</td>
                                                    <td>{{queue.created_at}}</td>
                                                    <td id="wishlist" class="text-start">
                                                        <button type="button" onclick="delQueue('{{queue.id}}')" class="btn btn-outline-danger btn-rounded"><i class="fas fa-trash"></i> </button> </button>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>

                </div>
            </div>

<script>

   	const queue_url = "{% url 'user:delqueue' %}"

	function delQueue(id){

		var myHeaders = new Headers()
           myHeaders.append('X-CSRFToken', document.querySelector('[name=csrfmiddlewaretoken]').value)

           var formData = new FormData()
           formData.append('id', id)

			var requestOptions = {
               method: 'POST',
                headers: myHeaders,
                body: formData,
                redirect: 'follow',
            };

            response = fetch(queue_url, requestOptions)
            	.then(function(response) {
                    if (response.ok) {
                        response.json().then((data) => {
                            if (data.success) {
								location.reload()
                            }
                        })

                    }
                })

		}
</script>

{% endblock %}

templates/user/reset.html
{% load static %}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Şifrəni Yenilə</title>
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/auth.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <div class="auth-content">
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <img class="brand" src="{% static 'assets/images/main-logo.png' %}" width="180" alt="bootstraper logo">
                    </div>
                    <h6 class="mb-4 text-muted">Şifrəni Yenilə</h6>
                    <p class="text-muted text-start">Hesabınızın e-poçt adresini daxil edin.</p>
                    <form method="post">
						{% csrf_token %}
                        <div class="mb-3 text-start">
                            {{ resetPassForm.email.label }}
							{{ resetPassForm.email }}

                            {% if resetPassForm.email.errors %}
								{% for error in resetPassForm.email.errors %}
									<li style="color: red">{{ error|escape }} </li>
								{% endfor %}
							{% endif %}
                        </div>
                        <button class="btn btn-primary shadow-2 mb-4">Göndər</button>
                    </form>
                    <p class="mb-0 text-muted">Hesabınız yoxdur? <a href="/user/register/">Qeydiyyatdan Keçin</a></p>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/user/wishlist.html
{% extends 'user-base.html' %}
{% block body %}
{% load static %}

{{ block.super }}

            <div class="content">
                <div class="container-fluid">
                    <div class="page-title">
                        <h3>İstək Siyahısı</h3>
                    </div>

                    {% csrf_token %}

					 <div class="col-md-12 col-lg-12">
                            <div class="card">
                                <div class="card-header">İstək siyahısına əlavə etdikləriniz</div>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Adı</th>
                                                    <th>Kira Qiyməti</th>
                                                    <th>Anbar</th>
                                                    <th>Məhsul Siyahısı</th>
                                                    <th>Siyahıdan Sil</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            {% for wish in wishlist %}
                                                <tr>
                                                    <td>{{wish.name}}</td>
                                                    <td>{{wish.rent}} AZN</td>
                                                    <td>{{wish.warehouse}}</td>
                                                    <td>{% if wish in wish_books %} Əlavə edilib {% else %}<a href="/detail/{{wish.id}}" class="btn btn-outline-success">Əlavə Et <i class="fas fa-cart-plus"></i></a> {% endif %}</td>
                                                    <td id="wishlist" class="text-start">
                                                        <button type="button" onclick="delWish('{{wish.id}}')" class="btn btn-outline-danger btn-rounded"><i class="fas fa-trash"></i> </button> </button>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <nav aria-label="Page navigation example">
                          <ul class="pagination justify-content-center">
                            <li class="page-item">
                              {% if wishlist.has_previous %}
                              <a class="page-link" href="?page={{ wishlist.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                              </a>
                              {% endif %}
                            </li>
                            {% for i in wishlist.paginator.page_range %}
                            <li class="page-item{% if wishlist.number == i %} active{% endif %}"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                            {% endfor %}
                            <li class="page-item">
                              {% if wishlist.has_next %}
                              <a class="page-link" href="?page={{ wishlist.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                              </a>
                              {% endif %}
                            </li>
                          </ul>
                        </nav>

                </div>
            </div>

<script>

   	const wish_url = "{% url 'user:delwish' %}"

	function delWish(id){

		var myHeaders = new Headers()
           myHeaders.append('X-CSRFToken', document.querySelector('[name=csrfmiddlewaretoken]').value)

           var formData = new FormData()
           formData.append('id', id)

			var requestOptions = {
               method: 'POST',
                headers: myHeaders,
                body: formData,
                redirect: 'follow',
            };

            response = fetch(wish_url, requestOptions)
            	.then(function(response) {
                    if (response.ok) {
                        response.json().then((data) => {
                            if (data.success) {
                                    location.reload()
                                }
                        })

                    }
                })

		}
</script>

{% endblock %}